return {
  {
    "zbirenbaum/copilot.lua",
    cmd = "Copilot",
    build = ":Copilot auth",
    opts = {
      suggestion = { enabled = false },
      panel = { enabled = false },
      filetypes = {
        terraform = true,
        yaml = true,
        markdown = true,
        toml = true,
        json = true,
        lua = true,
        python = true,
        rust = true,
        javascriptreact = true,
        javascript = true,
        typscriptreact = true,
        typescript = true,
        html = true,
        css = true,
        scss = true,
        less = true,
        graphql = true,
        dockerfile = true,
        sh = true,
        zsh = true,
        bash = true,
        vim = true,
        go = true,
        java = true,
        dotnet = true,
        help = true,
      },
    },
  },
}
