on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for RC Branches
        id: rc-branch
        run: |
          echo "Branch ${{ github.ref_name }}"
          if [[ ${{ github.ref_name }} == "r/[0-9]+\.[0-9]+\.[0-9]+" ]]; then
          echo "is_rc_branch=true" >> $GITHUB_OUTPUT
          else "is_rc_branch=false" >> $GITHUB_OUTPUT
          fi
